// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 11:53:07 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/arshiarah/Documents/GitHub/Vindio1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/plugins/**/*.{js,ts,mjs}","/Users/arshiarah/Documents/GitHub/Vindio1/composables/**/*.{js,ts,mjs}","/Users/arshiarah/Documents/GitHub/Vindio1/utils/**/*.{js,ts,mjs}","/Users/arshiarah/Documents/GitHub/Vindio1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/arshiarah/Documents/GitHub/Vindio1/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;