// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/5/2025, 10:35:46 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/D5/Vindio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/plugins/**/*.{js,ts,mjs}","C:/Users/D5/Vindio/composables/**/*.{js,ts,mjs}","C:/Users/D5/Vindio/utils/**/*.{js,ts,mjs}","C:/Users/D5/Vindio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/D5/Vindio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;